services:
  starlight:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app:delegated
      - node_modules:/app/node_modules
      - pnpm-store:/app/.pnpm-store

volumes:
  node_modules:
  pnpm-store:
